services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/app/data/sqlite.db
      - NEXTAUTH_SECRET=your-nextauth-secret-key
      - NEXTAUTH_URL=http://localhost:3001
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./prisma:/app/data
    restart: always