services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=file:/app/data/sqlite.db
      - NEXTAUTH_SECRET=your-nextauth-secret-key
      - NEXTAUTH_URL=http://localhost:3001
      - NODE_ENV=production
      - PORT=3001
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.chillbreaker.rule=Host(`chillbreaker.club`)"
      - "traefik.http.routers.chillbreaker.entrypoints=websecure"
      - "traefik.http.routers.chillbreaker.tls=true"
      - "traefik.http.routers.chillbreaker.tls.certresolver=letsencrypt"
      - "traefik.http.services.chillbreaker.loadbalancer.server.port=3001" 
    volumes:
      - ./prisma:/app/data
    restart: always
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
